### ISSUE TITLE
APIの仕様変更

### ISSUE THREAD

**Issue by Yuki-k-lion** [nocox/asakatu-kun#100]
## 目的・背景
フロントの実装を進めているといろいろと気が付いてしまったのでイシューをたてます。

### イベント情報のAPI
・イベント名がない
・お店の位置情報（簡易的なもので）
・イベント詳細（概要説明）がない
→全部必要。

・日時の形式が違う
→フロントで整形すれば大丈夫

・“duration”:
→これは使ってない
→でも終了時間の計算で必要
→フロントで計算が必要になる。

・“seatInfo”:
→UIに反映されてない…CDO！

### イベント参加ユーザーのAPI
・イベント参加ユーザーのレスポンスに「コメント」がない
・ユーザーステイタスのレスポンスに「どの絵文字を設定しているか」という情報がない

### 多分これはadditional
・GoogleMap/詳細な店舗の位置情報が含まれていない
・お店のリンクとかつけなかったっけ

## 満たすべき要求（テスト）
- [ ]

## TaskList
+ [ ]

## 留意事項
+

## 検討事項
+

**Comment by Yuki-k-lion** [comment]
相談。
フロントでもがっつり処理書くのか、バックエンドで全部書くのか。

**Comment by projectormato** [comment]
一旦バックエンドのAPI作ってから修正します！

**Comment by projectormato** [comment]
> フロントでもがっつり処理書くのか、バックエンドで全部書くのか。
バックエンドで処理する！！

**Comment by projectormato** [comment]
イベント名がない
・お店の位置情報（簡易的なもので）
・イベント詳細（概要説明）がない
つける

日時の形式が違う
デザイン用のStringを新しくレスポンスとして返す
ソートして渡す

・“duration”:
上と同じ

Createイベントの時フロントはduration投げないので、開始と終わりからduration計算する


イベント参加ユーザーのレスポンスに「コメント」がない
・ユーザーステイタスのレスポンスに「どの絵文字を設定しているか」という情報がない
大丈夫そう
