### ISSUE TITLE
APIエンドポイント設計

### ISSUE THREAD

**Issue by projectormato** [nocox/asakatu-kun#11]
APIのエンドポイントをフロントと話し合って決定する。
JSONの内容まで決める。

**Comment by projectormato** [comment]
土曜やる

**Comment by Yuki-k-lion** [comment]
もし `README.md` に特に書くことないならそこにパスだけ書いておいてもいいのかなと思った。

**Comment by projectormato** [comment]
とりあえずWiki書く！

**Comment by projectormato** [comment]
Wiki書いた！
https://github.com/nocox/asakatu-kun/wiki/API
とりあえず設計は終わったので、こっちはcloseして続きは #12 で
