### ISSUE TITLE
フロントのための、モックサーバーを作成する

### ISSUE THREAD

**Issue by projectormato** [nocox/asakatu-kun#12]
フロントのテストのしやすさと、
フロントとバックエンドの開発上の意思疎通のためにモックサーバを作成する。
調査も含む。

**Comment by projectormato** [comment]
とりあえず調査
[Java製](https://dev.classmethod.jp/server-side/mock-servers/)
[Node製](https://chaika.hatenablog.com/entry/2019/01/07/083000)
[Go製](https://tech.naitwo.me/entry/mock_server)

なんかWebサービス的なのがあって、ブラウザでポチポチするだけかなと思っていたけど、結構ちゃんと作らないといけない感じなのかな

**Comment by nocox** [comment]
[Swagger](https://swagger.io/tools/swagger-editor/)
これ良さげじゃない？

**Comment by projectormato** [comment]
ここで作成を行っています。
https://app.swaggerhub.com/apis/projectormato/asakatu-kun/1.0.0
