### ISSUE TITLE
ログイン状態が変わらない問題をどうにかする。

### ISSUE THREAD

**Issue by Yuki-k-lion** [nocox/asakatu-kun#124]
## 目的・背景
なぜか `store.js`での値がかわらない…

## 満たすべき要求（テスト）
- [ ]

## TaskList
+ [ ]

## 留意事項
+

## 検討事項
+

**Comment by projectormato** [comment]
ログインはhttps://github.com/nocox/asakatu-kun/pull/104 で実装されたようなのでCloseします！
