### ISSUE TITLE
イベント詳細がない

### ISSUE THREAD

**Issue by nocox** [nocox/asakatu-kun#168]
## 目的・背景
![image](https://user-images.githubusercontent.com/50159106/64918920-904aa280-d7df-11e9-8925-932710c4af31.png)

DBにすら存在してないです．
イベント作成ページでは用意されていますが，postでbackend側には送信していない状態

## 概要
影響がある機能
- イベント作成
- イベントページ
- イベント一覧ページ

## 満たすべき要求（テスト）
- [ ]

## TaskList
+ [ ]

## 留意事項
+

## 検討事項
+

**Comment by projectormato** [comment]
DDLにも無い感じか、欲しい気がしたので初期リリースProjectに一旦入れておきます
