### ISSUE TITLE
ユーザステータスAPI

### ISSUE THREAD

**Issue by projectormato** [nocox/asakatu-kun#21]

**Comment by yuza-plan** [comment]
```
{
  "status": 200,
  "data": {
    "statusId": 1,
    "userName": "asakatu-kun",
    "displayName": "朝活くん",
    "imagePath": "https://avatars0.githubusercontent.com/u/50159106",
    "content": "https://4.bp.blogspot.com/-m56DCo_VDbQ/UU--ubQ1vTI/AAAAAAAAO84/CWFZIAw-zxY/s1600/kaizoku_mark.png",
    "comment": "おしゃべりしたい！"
  }
}
```

`content`ってなに？

**Comment by yuza-plan** [comment]
`statusId `はDB的には`user_status_master_id`ってことで認識あってる？

**Comment by yuza-plan** [comment]
ユーザステータスAPIの要件ってもしかして
- ユーザーステータスの追加
- ユーザーステータス閲覧
の2つの要件が含まれている？

**Comment by yuza-plan** [comment]
> statusId はDB的にはuser_status_master_idってことで認識あってる？
statusIdはuser_status_idか
> contentってなに？
contentにcontent(enum)の画像パスか

**Comment by yuza-plan** [comment]
enumの使い方に苦戦、、、
とりあえず、contentなしで実装しました

**Comment by yuza-plan** [comment]
<img width="663" alt="ScreenShot 2019-07-23 0 04 15" src="https://user-images.githubusercontent.com/41431021/61646952-377ef200-ace7-11e9-9b35-f583bbde95ff.png">

**Comment by projectormato** [comment]
今気付いたその通りです！`content`一旦無しで良いと思う！

**Comment by yuza-plan** [comment]
自分以外のステータスを編集しようとした時に返すのは`OkResponse`と同じように`AuthErrorResponse`みたいに作ったほうがよいよね？
