### ISSUE TITLE
デザインのモック作成(ログイン以外)

### ISSUE THREAD

**Issue by Yuki-k-lion** [nocox/asakatu-kun#33]
XDで動くモックを作成する。
作成したもののURLなどはwikiかどこかに残しておいてもらえると助かる。
なんなら一旦それもgit管理してもいいかもね。
と思っている。

**Comment by Yuki-k-lion** [comment]
イベント作成画面ほしいーなー

**Comment by projectormato** [comment]
出来てそう？Project移行につきCloseします！
