### ISSUE TITLE
PRテンプレートの作成

### ISSUE THREAD

**Issue by projectormato** [nocox/asakatu-kun#5]
テンプレートあった方が、レビューする時も作成する時も楽かもしれない

**Comment by Yuki-k-lion** [comment]
@projectormato 
Is this issue already done?

**Comment by projectormato** [comment]
IssueのcloseをPOとするのもありかなあ、でも難しいか

**Comment by Yuki-k-lion** [comment]
なるほど。
それありだと思う。

けどテンプレートのことわかるかな。
具体的な機能からでいい気もする。

**Comment by projectormato** [comment]
おっけーじゃあ閉じるわ
