### ISSUE TITLE
JDBCの設定

### ISSUE THREAD

**Issue by projectormato** [nocox/asakatu-kun#7]

**Comment by nocox** [comment]
mysqlはdockerで立ち上がるが、springbootと繋がっていない状態 

- [ ] mavenで、必要なライブラリの依存関係を設定
- [ ] mysql側の情報をリソースに設定(コンテナ間接続を想定)
- [ ] Autowiredアノテーションの挙動確認
- [ ] INSERT 、SELECT が動くことを確認

[参考ブログ](http://yutty.hatenablog.jp/entry/2017/03/12/164747)
